{"Rows":[{"lon":"68731238","maplat":"22858437","thresholdShort":"","trAreaStatus":"","areaMaxspeed":"880","lineWidth":"","inflectionId":"43664152","pointOrder":"0","superspeedTimes":"8","thresholdLong":"","areaId":"43664151","lineTimes":"","id":"43664156","areaMinspeed":"0","highwayId":"43664153","maplon":"68734752","superlowspeedTimes":"0","lat":"22858126"},{"lon":"68915842","maplat":"22744164","thresholdShort":"","trAreaStatus":"","areaMaxspeed":"880","lineWidth":"","inflectionId":"43664154","pointOrder":"1","superspeedTimes":"8","thresholdLong":"","areaId":"43664151","lineTimes":"","id":"43664157","areaMinspeed":"0","highwayId":"43664155","maplon":"68919322","superlowspeedTimes":"0","lat":"22743837"}],"Total":"0"}