{"Rows":[{"teamName":"","sumOverrpmTimestr":"","sumUrgentSpeedTimestr":"","sumGearGlideTime":"0","sumOverrpmAlarm":"0","sumOverspeedAlarm":"21","teamId":"","sumUrgentSpeedNum":"0","corpName":"","sumUrgentLowdownNum":"0","lineName":"","sumOverrpmTime":"0","sumGearGlideTimestr":"","sumUrgentSpeedTime":"0","sumOverspeedTimestr":"00:16:11","sumUrgentLowdownTime":"0","vid":"","lineId":"","vehicleNo":"","sumMileage":"63811.4","corpId":"","sumOilWear":"0.0","sumFatigueTimestr":"407:10:41","sumUrgentLowdownTimestr":"","sumOilwearMileage":"0.0","statDate":"","statYear":"","countVehicle":"42","vinCode":"","statDateStr":"","vehicleType":"","sumFatigueAlarm":"63","statMonth":"","sumOverspeedTime":"971","sumFatigueTime":"1465841","sumGearGlideNum":"0","innerCode":""}],"Total":"3"}