[{"alarmDate":"2013-4-8","generalCount":"0","seriousCount":"0","suggestionCount":"146","urgentCount":"2"},{"alarmDate":"2013-4-9","generalCount":"0","seriousCount":"0","suggestionCount":"380","urgentCount":"4"},{"alarmDate":"2013-4-10","generalCount":"0","seriousCount":"0","suggestionCount":"386","urgentCount":"5"},{"alarmDate":"2013-4-11","generalCount":"0","seriousCount":"0","suggestionCount":"459","urgentCount":"10"},{"alarmDate":"2013-4-12","generalCount":"0","seriousCount":"0","suggestionCount":"135","urgentCount":"15"},{"alarmDate":"2013-4-13","generalCount":"0","seriousCount":"0","suggestionCount":"88","urgentCount":"17"},{"alarmDate":"2013-4-14","generalCount":"0","seriousCount":"0","suggestionCount":"129","urgentCount":"6"}]