[{"descriptions":"通行提示：由于S237线(大练线)河南省郑州市登封市卢店镇至巩义交界段(K112+816至K128+104)进行公路施工养护，该路段于2012年08月23日08时采取双向封闭的措施，预计2014年11月23日08时恢复通行。请驾驶员注意沿途设立的绕行、禁行等警告、警示标志，小心驾驶。suijishu","provinceCode":410000,"roadConditionTime":"2013-04-16 17:45"},{"descriptions":"通行提示：由于S316线(郑登线)河南省郑州市新密市白寨镇王寨河段(K18+650至K18+700)进行桥隧施工养护，该路段于2012年04月28日08时采取双向封闭的措施，预计2015年04月28日08时恢复通行。请驾驶员注意沿途设立的绕行、禁行等警告、警示标志，小心驾驶。suijishu","provinceCode":410000,"roadConditionTime":"2013-04-16 17:45"}]