{"address":"","birthday":0,"bussinessId":"","cardId":"110152198412158007","cardType":"","cmpasswd":"","cqpasswd":"","createBy":122205,"createTime":1366097353164,"driverChdate":0,"driverNo":"123456987456","driverValdate":0,"drivercardDep":"","email":"","emgcContactor":"","emgcPhone":"","enableFlag":"1","entId":"122195","fax":"","fixedphone":"","incareerDate":0,"mobilephone":"13801145785","postcode":"","sex":"1","staffCode":"","staffId":43647218,"staffName":"刘明哲","staffState":"1","staffType":"0","updateBy":0,"updateTime":0,"vehicleNo":"","vehiclephone":"","vid":0}