{"businessLicense":"","businessScope":"","certificateOffice":"","corpBoss":0,"corpBusinessno":"","corpCity":"320500","corpCode":"600025","corpCountry":"","corpEconomytype":"","corpLevel":"2","corpPaystate":0,"corpPaytype":0,"corpProvince":"320000","corpQuale":"091","createBy":121049,"createByName":"张帆","createTime":1348030375989,"enableFlag":"1","entId":122218,"entName":"常熟新海华汽车客运服务有限公司","entState":"1","entType":1,"isdeteam":"0","licenceNo":"","licenceWord":"","orgAddress":"","orgCfax":"","orgCmail":"","orgCname":"","orgCno":"","orgCphone":"","orgCzip":"","orgLogo":"defaultImg.png","orgMem":"","orgShortname":"常熟新海华汽车客运","parentId":122194,"parentName":"苏州欧迅达数字交通技术有限公司","seqCode":"","specialId":"","updateBy":122194,"updateTime":1357267716892,"url":""}