[{"NODE_TYPE_VEHICLE":"","text":"苏州欧迅达数字交通技术有限公司","isexpand":"true","ENT_TYPE_NOCORP_AND_NOTEAM":"","NODE_TYPE_TEAM":"","NODE_TYPE_LINE":"","id":"122194","parentId":"122192","entType":"1","corpLevel":"3","value":"600025","childrenList":[{"NODE_TYPE_VEHICLE":"","text":"常熟新海华汽车客运服务有限公司","isexpand":"false","ENT_TYPE_NOCORP_AND_NOTEAM":"","NODE_TYPE_TEAM":"","NODE_TYPE_LINE":"","id":"122218","parentId":"122194","entType":"1","corpLevel":"2","value":"600025","childrenList":"","isdeteam":"0","nodeType":"1","NODE_TYPE_CORP":""}],"isdeteam":"0","nodeType":"1","NODE_TYPE_CORP":""}]