[{"vbrandCode":"2","enableFlag":"1","prodName":"KLQ6109QE4","prodDesc":"KLQ6109QE4","prodCode":"SZKL001"},{"vbrandCode":"2","enableFlag":"1","prodName":"KLQ6702E3","prodDesc":"KLQ6702E3","prodCode":"SZKL005"},{"vbrandCode":"2","enableFlag":"1","prodName":"KLQ6850D3","prodDesc":"KLQ6850D3","prodCode":"SZKL004"},{"vbrandCode":"2","enableFlag":"1","prodName":"KLQ6896E3","prodDesc":"KLQ6896E3","prodCode":"SZKL003"},{"vbrandCode":"2","enableFlag":"1","prodName":"KLQ6896QAE3","prodDesc":"KLQ6896QAE3","prodCode":"SZKL002"}]