[{"i":"122194","n":"苏州欧迅达数字交通技术有限公司","t":"1","p":"122192","o":"0","s":"44","ov":"0","pv":"null","oem":"null","tel":"null","c":[{"i":"122218","n":"常熟新海华汽车客运服务有限公司","t":"1","p":"122194","o":"0","s":"41","ov":"0","pv":"null","oem":"null","tel":"null"},{"i":"122207","n":"欧迅达车队","t":"2","p":"122194","o":"0","s":"3","ov":"0","pv":"null","oem":"null","tel":"null"}]}]