{"businessLicense":"","businessScope":"","certificateOffice":"","corpBoss":0,"corpBusinessno":"","corpCity":"320100","corpCode":"600025","corpCountry":"","corpEconomytype":"","corpLevel":"3","corpPaystate":0,"corpPaytype":0,"corpProvince":"320000","corpQuale":"101","createUtc":0,"entId":122194,"isdeteam":"0","licenceNo":"","licenceWord":"","orgAddress":"","orgCfax":"","orgCmail":"","orgCname":"","orgCno":"","orgCphone":"","orgCzip":"","orgLogo":"http://www.zjyypt.com/ReportApp/reportfile/images/corpLogo/images/corpLogo/defaultImg.png","orgMem":"","orgShortname":"苏州欧迅达数字交通技术有限公司","specialId":"","url":""}