[{"msgIdx":"疲劳","enableFlag":"1","createUtcStr":"2013-04-09 14:31:29.0","opId":"138422","opName":"榆阳分公司","msgBody":"你已疲劳驾驶，请靠边停车。","msgId":"513787","msgType":"1","isShared":"1","createUtc":"1365489088794"},{"msgIdx":"您已超速请慢行","enableFlag":"1","createUtcStr":"2013-04-06 20:53:11.0","opId":"144644","opName":"石国华","msgBody":"您好，你已超速，请慢行，不然将对您进行罚款，市运管处宣！","msgId":"500530","msgType":"1","isShared":"1","createUtc":"1365252791125"}]