{"accessoryFlag":0,"createBy":122866,"createTime":1350538056703,"enableFlag":"1","enddate":1350576001000,"entId":122807,"infoContent":"<p>所有公司与明日下午两点在时迈科技公司开会、<\/p>","infoId":13001341,"infoStatus":"1","infoTheme":"通知","infoType":"002","isSettop":1,"msgType":"企业公告","publicInfoTime":"2012-10-18 13:27:43","publishTime":1350538063064,"publishUser":0,"sysTime":0,"updateBy":0,"updateTime":1350538262425,"userName":"系统管理员"}